- name: Install Redis
  hosts: [django_boilerplate_redis]
  become: true

  tasks:
    # Setup Redis

    - name: Install Redis
      apt:
        name: redis-server
        state: present
      tags: ['setup']

    - name: Enable Redis to start at boot
      systemd:
        name: redis-server
        enabled: true
      tags: ['setup']
