version: "3.9"

services:
  web:
    container_name: django
    build: .
    command: /app/entrypoint/dev-run-web.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.postgres-data/db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2.6-alpine

  celery:
    container_name: worker
    restart: always
    build:
      context: .
    command: watchmedo auto-restart -d . -p '*.py' --recursive -- celery -A core.celery_worker worker -B -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - web
