version: "3.9"

services:
  web:
    container_name: django
    build: .
    command: gunicorn wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.postgres-data/db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2.6-alpine

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A core.celery_worker worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - web

  celery_beat:
    container_name: celery_beat
    restart: always
    build:
      context: .
    command: celery -A core.celery_worker beat -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - web
      - celery
