---
- name: Setup Ubuntu initial configuration
  hosts: [general_purposes_webserver]

  vars:
    project_local_path: "{{ playbook_dir }}/../../../cloudatlas_blog"
    project_path: /home/ubuntu/cloudatlas_blog
    virtualenv_path: "{{ project_path }}/venv"

  tasks:
    - name: Update and upgrade Apt
      become: true
      apt:
        update_cache: yes
        upgrade: yes
      tags: ['setup', 'update_packages']

    - name: Install APT Packages
      become: true
      apt: name={{ item }} update_cache=yes state=latest
      loop: [
        # Tools
        'git',
        'vim',
        'wget',
        'less',
        'fish',
        'tmux'
      ]
      tags: ['setup', 'update_packages']

    - name: Change default shell to fish
      become: true
      shell: chsh -s /usr/bin/fish ubuntu
      tags: ['setup']

    - name: Set tmux config file
      copy:
        src: "{{ project_local_path }}/deployment/config_files/tmux.conf"
        dest: "~/.tmux.conf"
      tags: ['setup', 'update']
